//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public string MAHD { get; set; }
        public Nullable<int> SOSAO { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
