//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUDUNGPKM
    {
        public string MAPKM { get; set; }
        public string MATK { get; set; }
        public Nullable<int> NGAYSUDUNG { get; set; }
        public Nullable<double> SOTIENGIAM { get; set; }
    
        public virtual PHIEUKHUYENMAI PHIEUKHUYENMAI { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
