//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHUYENMAI()
        {
            this.LICHSUDUNGPKMs = new HashSet<LICHSUDUNGPKM>();
        }
    
        public string MAPKM { get; set; }
        public string LOAIPHIEU { get; set; }
        public Nullable<int> GIATRI { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
        public string DIEUKIEN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUDUNGPKM> LICHSUDUNGPKMs { get; set; }
    }
}
