//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.LICHSUDUNGPKMs = new HashSet<LICHSUDUNGPKM>();
        }
    
        public string MATK { get; set; }
        public string ID { get; set; }
        public string TENTK { get; set; }
        public string MATKHAU { get; set; }
    
        public virtual GIOHANG GIOHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUDUNGPKM> LICHSUDUNGPKMs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
